environment:
  matrix:
    - PYTHON: "C:\\Python27_64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "27"
      CONDA_NPY: "111"
      CHIMERA_VERSION: "1.12"
      CHIMERADIR: "C:\\Python27_64\\Library\\Chimera 1.12"
      PYTHONDONTWRITEBYTECODE: "1"

matrix:
  fast_finish: true

cache:
  - '%PYTHON%'

install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit),
  # as well as pip, conda-build
  - ps: if (!(Test-Path $env:PYTHON\\Scripts\\conda.exe -PathType Leaf)){ .\\scripts\\install_miniconda.ps1 }
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "IF NOT EXIST ""%CHIMERADIR%"" conda build conda-recipes/ucsf-chimera"
  - "IF NOT EXIST ""%CHIMERADIR%"" conda install -y -q -c %PYTHON%/conda-bld ucsf-chimera"
  - conda install -y -q pytest
  - conda build purge
  - python setup.py install

build: off

test_script:
  - cd tests
  - pytest
  - python pychimeratest.py pychimera_test*