environment:
  matrix:
    - PYTHON: "C:\\Python27_64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "27"
      CONDA_NPY: "111"
      CHIMERA_VERSION: "1.12"

matrix:
  fast_finish: true

install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit),
  # as well as pip, conda-build
  - powershell .\\scripts\\install_miniconda.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda build conda-recipes/ucsf-chimera
  - conda install -y -q -c %PYTHON%/conda-bld ucsf-chimera
  - conda install -y -q pytest
  - python setup.py install
  - "SET CHIMERADIR=%PYTHON%\\Library\\Chimera %CHIMERA_VERSION%"
  - ECHO %CHIMERADIR%
  - pychimera --path
  - set PYTHONDONTWRITEBYTECODE="1"

build: off

test_script:
  - cd tests
  - pytest
  - python pychimeratest.py pychimera_test*