# Derived from https://github.com/theochem/qcgrids/blob/master/.travis.yml
env:
  matrix:
  - MYCONDAPY=2.7

####
# EVERYTHING BELOW THIS LINE WILL BE COPIED INTO OTHER YMLs
####

# Do not use Travis Python to save some time.
language: generic
os:
- linux
- osx
osx_image: xcode6.4
dist: trusty
sudo: false

matrix:
  # We only test on Linux with one specific Python version, unless we make a release. All
  # other cases are allowed to fail and will exit early. With the fast_finish option,
  # travis will send a status update to github as soon as the non-allowed-to-fail has
  # finished. This speeds up testing in PRs.
  #
  # This is not ideal. It would be better to run just one item from the build matrix when
  # not preparing a release. This is not possible on Travis. There are several tickets on
  # travis-ci related to this limitation.
  #
  #    https://github.com/travis-ci/travis-ci/issues/7451
  #    https://github.com/travis-ci/travis-ci/issues/7149
  #    https://github.com/travis-ci/travis-ci/issues/2778
  #    ...
  fast_finish: true
  allow_failures:
  - os: osx

cache:
  directories:
  - $HOME/download
  - $HOME/miniconda
  - $HOME/chimera

before_cache:
- if ! [[ $TRAVIS_TAG ]]; then rm -rf $HOME/miniconda/conda-bld; fi
- rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history
- pip uninstall -y pychimera

branches:
  only:
  - master
  - /^v?[0-9]+\.[0-9]+(\.[0-9]+)?([ab][0-9]+)?$/  # release branches

before_install:
# Get miniconda. Take the right version, so re-installing python is hopefully not needed.
- if test -e $HOME/miniconda/bin; then
    echo "miniconda already installed.";
  else
    echo "Installing miniconda.";
    rm -rf $HOME/miniconda;
    mkdir -p $HOME/download;
    if [[ -d $HOME/download/miniconda.sh ]]; then rm -rf $HOME/download/miniconda.sh; fi;
    if [ "${MYCONDAPY}" = "2.7" ]; then
      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O $HOME/download/miniconda.sh;
      fi;
    else
      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O $HOME/download/miniconda.sh;
      fi;
    fi;
    bash $HOME/download/miniconda.sh -b -p $HOME/miniconda;
  fi


install:
- source $HOME/miniconda/bin/activate
- hash -r

# Configure conda and get a few essentials
- conda config --set always_yes yes
- conda install -q conda conda-build pytest
# Show conda info for debugging
- conda info -a

# Check if UCSF Chimera is present and install it if needed
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    if [[ ! -e $HOME/miniconda/bin/chimera ]]; then
      CHIMERA_PACKAGE="ucsf-chimera-headless";
      conda build -q conda-recipes/$CHIMERA_PACKAGE;
      conda install -y -c $HOME/miniconda/conda-bld $CHIMERA_PACKAGE;
      ln -s $HOME/miniconda/bin/chimera-headless $HOME/miniconda/bin/chimera || true;
    fi;
  else
    if [[ ! -e $HOME/chimera/bin/chimera ]]; then
        set +x;
        echo "IMPORTANT - By downloading you accept the UCSF Chimera Non-Commercial Software License Agreement!";
        echo "IMPORTANT - The license agreement can be found at http://www.cgl.ucsf.edu/chimera/license.html";
        echo "IMPORTANT - If you do not agree, please press Ctrl-C now.";
        echo "IMPORTANT - Downloading in 10 seconds...'";
        sleep 10;
        set -x;
        _file="chimera-1.12-mac64.dmg";
        _filepath="mac64/${_file}";
        _downloader="https://www.rbvi.ucsf.edu/chimera/cgi-bin/secure/chimera-get.py";
        _download=`curl -s -F file="${_filepath}" -F choice=Accept "${_downloader}" | grep href | sed -E 's/.*href="(.*)">/\1/'`;
        curl "https://www.rbvi.ucsf.edu""${_download}" -o "${_file}";
        hdiutil convert "${_file}" -format UDRW -o chimerarw;
        hdiutil attach -mountpoint "$HOME/chimera" chimerarw.dmg;
        export CHIMERADIR="$HOME/chimera";
    fi;
  fi
- python setup.py install
# Show currently installed packages
- conda list

script:
- cd tests
- pytest
- python pychimeratest.py pychimera_test*
- cd ..

before_deploy:
- conda build conda-recipes/pychimera --no-test
- conda install anaconda-client

deploy:
  # Deploy to Anaconda.org
  - provider: script
    script: anaconda -t $ANACONDA_TOKEN upload -u insilichem $HOME/miniconda/conda-bld/**/pychimera-*.tar.bz2
    on:
      tags: true
  # Deploy to PyPI
  - provider: pypi
    username: jaimergp
    password:
      secure: JnDtXHS5IqL73rdk1tW8rrPZ5X3ZmwoR4CgvexLIEDyan2ykyyEFQ6+utS8nSwjrIAbQSUDD4iwux5B0n2HO5FVl8hjXTQa3SvyZ0w6vhRVD/7PQqqcBq7r3VkvJe3EHB4B7dUCI2VfqKB7ciCVE4E0pcMEvpK145eaLn+Z+0OqefOx/xO9cb8UaJW0ZbQrywyZl7+hfN9YND9HjXqg4yoZVYYudT1yT/O5ekXggYOVqU1dtzM2i6LLzfKJ2DLJOCdlH5yhpALaECxBAkQKucuW28GJhH7ScMKBMrMs8HHjItCK061KMCBY30uxHiny28T2ov0pB1ng/py+14eJfQ+1KIRAAorkZqQNlvGPgoJ3qx7wIs2AOKv9nR+dvDwzQYteAshL5xkBi1iqrUuYQWqdnrHni30Yn0k1h+5Hqmq1n3yy2tBl6DqBvvnEzqXrZ2+H1I/em9SBGBqQOY9nLAFMkFx8zKnqSQxCExX/IrXSWR1mjucStJjhV67hyIYhAknoRSaulHhmAxRP7WIiMVCJa9nJy8w75rtsQkatywZhwwbB7h+TmXOGhQ9OaJKG4UVNIHxoLA8WbUTr/DSfGesRZ1wNzri91gKjFBeO2CFdKN4XvgJBGnqiSer0bMvhPrlZdbpQkcO972O2rjbs7AcbCn1Zu2PNdDmFzUh2wY+Y=
    on:
      tags: true
