# Derived from https://github.com/theochem/qcgrids/blob/master/.travis.yml
env:
  matrix:
  - MYCONDAPY=2.7

####
# EVERYTHING BELOW THIS LINE WILL BE COPIED INTO OTHER YMLs
####

# Do not use Travis Python to save some time.
language: generic
os:
- linux
- osx
osx_image: xcode6.4
dist: trusty
sudo: false

matrix:
  # We only test on Linux with one specific Python version, unless we make a release. All
  # other cases are allowed to fail and will exit early. With the fast_finish option,
  # travis will send a status update to github as soon as the non-allowed-to-fail has
  # finished. This speeds up testing in PRs.
  #
  # This is not ideal. It would be better to run just one item from the build matrix when
  # not preparing a release. This is not possible on Travis. There are several tickets on
  # travis-ci related to this limitation.
  #
  #    https://github.com/travis-ci/travis-ci/issues/7451
  #    https://github.com/travis-ci/travis-ci/issues/7149
  #    https://github.com/travis-ci/travis-ci/issues/2778
  #    ...
  fast_finish: true

cache:
  directories:
  - $HOME/download
  - $HOME/miniconda
  - $HOME/chimera

before_cache:
- if [[ ! $TRAVIS_TAG ]]; then rm -rf $HOME/miniconda/conda-bld; fi
- rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history
- pip uninstall -y pychimera

branches:
  only:
  - master
  - /^v?[0-9]+\.[0-9]+(\.[0-9]+)?([abc][0-9]*)?$/  # release branches

before_install:
# Get miniconda. Take the right version, so re-installing python is hopefully not needed.
- if test -e $HOME/miniconda/bin; then
    echo "miniconda already installed.";
  else
    echo "Installing miniconda.";
    rm -rf $HOME/miniconda;
    mkdir -p $HOME/download;
    if [[ -d $HOME/download/miniconda.sh ]]; then rm -rf $HOME/download/miniconda.sh; fi;
    if [ "${MYCONDAPY}" = "2.7" ]; then
      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O $HOME/download/miniconda.sh;
      fi;
    else
      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O $HOME/download/miniconda.sh;
      fi;
    fi;
    bash $HOME/download/miniconda.sh -b -p $HOME/miniconda;
  fi


install:
- source $HOME/miniconda/bin/activate
- hash -r

# Configure conda and get a few essentials
- conda config --set always_yes yes
- conda install -q conda conda-build pytest
# Show conda info for debugging
- conda info -a

# Check if UCSF Chimera is present and install it if needed
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    if [[ ! -e $HOME/miniconda/bin/chimera ]]; then
      CHIMERA_PACKAGE="ucsf-chimera-headless";
      conda build -q conda-recipes/$CHIMERA_PACKAGE;
      conda install -y -c $HOME/miniconda/conda-bld $CHIMERA_PACKAGE;
      ln -s $HOME/miniconda/bin/chimera-headless $HOME/miniconda/bin/chimera || true;
    fi;
  else
    if [[ ! -e $HOME/chimera/Chimera.app/Contents/Resources/bin/chimera ]]; then
        set +x;
        echo "IMPORTANT - By downloading you accept the UCSF Chimera Non-Commercial Software License Agreement!";
        echo "IMPORTANT - The license agreement can be found at http://www.cgl.ucsf.edu/chimera/license.html";
        echo "IMPORTANT - If you do not agree, please press Ctrl-C now.";
        echo "IMPORTANT - Downloading in 10 seconds...'";
        sleep 10;
        set -x;
        _file="chimera-1.12-mac64.dmg";
        _filepath="mac64/${_file}";
        _downloader="https://www.rbvi.ucsf.edu/chimera/cgi-bin/secure/chimera-get.py";
        _download=`curl -s -F file="${_filepath}" -F choice=Accept "${_downloader}" | grep href | sed -E 's/.*href="(.*)">/\1/'`;
        curl "https://www.rbvi.ucsf.edu""${_download}" -o "${_file}";
        hdiutil convert "${_file}" -format UDRW -o chimerarw;
        hdiutil attach -mountpoint "$HOME/chimera" chimerarw.dmg;
        rm -rf $HOME/chimera/Chimera.app/Contents/Resources/lib/python2.7/site-packages/setuptools*;
        pip install -U setuptools -t $HOME/chimera/Chimera.app/Contents/Resources/lib/python2.7/site-packages;
    fi;
    export CHIMERADIR="$HOME/chimera/Chimera.app/Contents/Resources";
  fi
# Show currently installed packages
- conda list
- python setup.py install

script:
- cd tests
- pytest
- python pychimeratest.py pychimera_test*
- cd ..
- if [[ $TRAVIS_TAG ]]; then
    conda build conda-recipes/pychimera --no-test;
    conda install -q anaconda-client;
    anaconda -t $ANACONDA_TOKEN upload -u insilichem $HOME/miniconda/conda-bld/**/pychimera-*.tar.bz2;
  fi;

deploy:
  # Deploy to PyPI
  - provider: pypi
    username: jaimergp
    skip_cleanup: true
    password:
      secure: rLTkUZshTVFYbZ79EREfLcl9jwwE0Yy8lmSnmRkka077zs86yaClw+sEKaDdINyjKasC0+9DA2qMKNEHvewKDHfIarA9/ZLfcyTWusiiJrAMF5oqomfQV9gy0Ofso6YDggzzuEbRhCVNeS2BeWczbJ4esUCRTdx+2hIMhcqe6whEHK9nw/M4IvNqoo4vyjS/2H1yOBXstfvRx6NKBFVa8FyLcLE0UDRMAmHg0WGmDgu7ch3H3jyx5tG8dodvoCyVYKMm1aHLvUyHmHnrcw4/zjZhUeeIVY0lMIVDNwQ+5LuceAASEdMGrfkdZWuQOjjUosHUJMs6apIbQ+L8fXyBiPJ2VZ/TAm4RqSSfwfACMoaCLxszIc3yP/kXnKjmvqFdpTVumUuI+kqkd0gk1Ai4HxUZK9unybtIoWtUwT36h4+AFLQw/mL5ekuOQ2MgRA9g/n1f3iwG9T+lEaSoQxq4O7o5DViazi/Y+4gaHYwKGvF78ZrQuzwh2TZZQnbBoafCpyqQGLtYZNvemEwplPf4lEnxI30MXAvpLx8YoF/ooqNoUu90JjgDSSWnfaqXh5E4xhlvYoW3duNzCd1J13ebbiU6rEH8Pw7pDEJrByfSpZp4wisyuyPV3oaygy8d0Md7Ad7lYxurjP1+qHi1lDVLyMFQCa40I9GY5C766hRJZ0Y=
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"