package:
  name: ucsf-chimera
  version: "1.12"

about:
  home: https://www.cgl.ucsf.edu/chimera/
  license: UCSF Chimera Non-Commercial Software License
  summary: Extensible Molecular Modeling System

requirements:
  build:
    - curl
    - git  # [win]
    - gnuwin32  # [win]
    - python 2.7*
