package:
  name: ucsf-chimera-headless
  version: "1.11"

about:
  home: https://www.cgl.ucsf.edu/chimera/
  license: UCSF Chimera Non-Commercial Software License
  summary: Extensible Molecular Modeling System

requirements:
  build:
    - curl
    - unxutils  # [win]
    - python 2.7*
