package:
  name: pychimera
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v')[1:] }}

about:
  home: https://github.com/insilichem/pychimera
  license: LGPL
  summary: Use UCSF Chimera Python API in a standard Python 2.7 interpreter.

source:
  git_url: https://github.com/insilichem/gaudi.git
  git_tag: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

requirements:
  build:
    - python 2.7*
    - setuptools

  run:
    - python 2.7*

test:
  imports:
    - pychimera
  commands:
    - pychimera -c "import chimera"
