package:
  name: pychimera
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v')[1:] }}

about:
  home: https://github.com/insilichem/pychimera
  license: LGPL
  summary: Use UCSF Chimera Python API in a standard Python 2.7 interpreter.

source:
  path: ../../
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v')[1:]  }}

build:
  skip_compile_pyc:
    - "*.py"

requirements:
  build:
    - python 2.7*
    - setuptools

  run:
    - python 2.7*
    - nomkl
    - cairo 1.12.18  # [linux]
    - freetype 2.5.5  # [unix]
    - fontconfig 2.12 # [linux]
    - glib 2.50.2  # [linux]
    - icu 54.1  # [unix]
    - libgcc 5.2.0  # [linux]
    - libiconv 1.14  # [unix]
    - libpng 1.6.30  # [unix]
    - ncurses 6.0  # [unix]
    - pcre 8.39  # [unix]
    - pixman 0.32.6  # [linux]
    - readline 6.2  # [unix]
    - setuptools 27.2.0  # [unix]
    - sqlite 3.13.0  # [unix]
    - tk 8.5.18  # [unix]

test:
  imports:
    - pychimera
  commands:
    - pychimera -c "import chimera"
